### ISSUE TITLE
How to test on my own dataset?

### ISSUE THREAD

**Issue by Reed-yang** [KTH-RPL/SeFlow#3]
I saw [issue on Deflow](https://github.com/KTH-RPL/DeFlow/issues/3) that eval on custum dateset needs groud truth flow.
I'm very exciting that you have this self-supervised version of this model and wondering whether it is possible to inference scene flow using your pretrained weight on dataset: has frame point clouds, poses, and segmentation maybe, then producing flow results.

**Comment by Reed-yang** [comment]
btw, is it possible to test on dataset that has no valid `ground_mask` available? Or is there a convenient way to compute `ground_height.npy` & `se2.json` on my aggregated point cloud (from all frames)?
thx in advance, :)

**Comment by Kin-Zhang** [comment]
You can directly try this python package to get ground_mask: https://github.com/Kin-Zhang/linefit/tree/master

**Comment by Reed-yang** [comment]
One more question, I noticed that in `process_log`, `pose` and `car_frame_pc` are input for model inference. What coordinate system is `car_frame_pc` established on, Can you explain it in detail? In each frame, is `car_frame_pc` ego-centric or is it based on a unified first moment as the origin (world coor)? What should I do if my data is in world coor?

**Comment by Kin-Zhang** [comment]
I think it's fine for both, `pc` is ego-centric and you will save pose for the world coor, and the first pose can be the original world coor.

**Comment by Reed-yang** [comment]
Hi, just want to confirm. In the scene flow task, is it assumed that: the vehicles (rigid body motion) are moving on the same horizontal plane? Because in the visualization I only see **2D motion angle**, which does not seem to be able to handle the situation of height changes?
If I'm wrong, please explain in detail, thx very much!

**Comment by Kin-Zhang** [comment]
The output is 3D vector which (fx,fy,fz) which is illustrated in the paper in the problem statement section I think.

The visualization is because that's more concise and easy to understand, you can check that in youtube presentation video there is an image showing a flow vector in a 3D way.

**Comment by Kin-Zhang** [comment]
Let me know if you have further questions.
