### ISSUE TITLE
`process.py` is still empty

### ISSUE THREAD

**Issue by Shiming94** [KTH-RPL/SeFlow#4]
Hi, thank you so much for open-sourcing such a good work! I noticed that the `process.py` is still empty, and I wonder when you could update it.

Best,
Shiming

**Comment by Kin-Zhang** [comment]
We have mentioned that `The process script will be public when the paper is published officially.`

While as I knew, the Springer was still on the way to publish officially, I will update it at the same time when it is officially published in volume.

**Comment by Shiming94** [comment]
Thank you so much for your quick reply. I have another question regarding the `extract_av2.py` script.

```python
def read_pose_pc_ground(data_dir: Path, log_id: str, timestamp: int, avm: ArgoverseStaticMap):
    log_poses_df = read_feather(data_dir / log_id / "city_SE3_egovehicle.feather")
    # more detail: https://argoverse.github.io/user-guide/datasets/lidar.html#sensor-suite
    ego2sensor_pose = read_ego_SE3_sensor((data_dir / log_id))['up_lidar']
    filtered_log_poses_df = log_poses_df[log_poses_df["timestamp_ns"].isin([timestamp])]
    pose = convert_pose_dataframe_to_SE3(filtered_log_poses_df.loc[filtered_log_poses_df["timestamp_ns"] == timestamp])
    pc = Sweep.from_feather(data_dir / log_id / "sensors" / "lidar" / f"{timestamp}.feather").xyz
    # transform to city coordinate since sweeps[0].xyz is in ego coordinate to get ground mask
    is_ground = avm.get_ground_points_boolean(pose.transform_point_cloud(pc))

    # NOTE(SeFlow): transform to sensor coordinate, since some ray-casting based methods need sensor coordinate
    pc = ego2sensor_pose.inverse().transform_point_cloud(pc) 
    return pc, pose, is_ground
```

As far as I understand, `pc = Sweep.from_feather(data_dir / log_id / "sensors" / "lidar" / f"{timestamp}.feather").xyz` will give a `pc` in ego coordinate, and the ground mask is defined in the city/global coordinate, right?

Then `pc = ego2sensor_pose.inverse().transform_point_cloud(pc) ` seems to transfer a `pc` from the sensor coordinate to the ego coordinate as you used `ego2sensor_pose.inverse()`, but here the input `pc` is already defined in ego coordinate. 

Is there something I understood wrongly?

**Comment by Kin-Zhang** [comment]
`pc` is in ego frame.

ground mask found in the global frame but will mask in each point, so it's align with each point in `pc`. Another way to do this is directly use ground segmentation algorithm. like this one: https://github.com/Kin-Zhang/linefit. Input your `pc` and you will get label directly.

**Comment by Shiming94** [comment]
Hi, thank you for your reply. 

If `pc` is already defined in the ego frame, then what does this transform `pc = ego2sensor_pose.inverse().transform_point_cloud(pc)` do?

**Comment by Kin-Zhang** [comment]
Let pc in ego sensor frame, since some methods need use correct sensor
original to do ray casting

**Comment by Shiming94** [comment]
But the transformation matrix `ego2sensor_pose.inverse()` seems to be used to transform a point cloud from the `sensor` (or maybe ego sensor) to the `ego` frame, as the matrix is inversed. So, if I understand correctly, here, the input `pc` is defined in the `ego` frame, but the transformation matrix is used to transform from `sensor` to `ego`; I think it doesn't match. Correct me if I was wrong here.

**Comment by Kin-Zhang** [comment]
If you confused please run visualization script directly (you can directly
download demo_data around 600mb), you can view that the data is correct and
the axis is on sensor original.

Looks data by yourself.

Or debug step by step to check data if you really confused

**Comment by Kin-Zhang** [comment]
all codes are ready now.
