### ISSUE TITLE
About Dataprocess environment conflict between Waymo-open-dataset-tf-2-11-0 and  Open3d

### ISSUE THREAD

**Issue by ligeng0197** [KTH-RPL/SeFlow#9]
Hello~ THanks for great work! When following your the data preprocessing steps to set up the processing environment ([this](https://github.com/KTH-RPL/SeFlow/blob/main/dataprocess/README.md#argoverse-20)), I encountered environment conflicts. The specific error message is as follows. I tried replacing the Waymo version with 1.6.1 (latest), but it still didn't resolve the issue.

```
The conflict is caused by:
    waymo-open-dataset-tf-2-11-0 1.5.1 depends on pillow==9.2.0
    open3d 0.18.0 depends on pillow>=9.3.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict
```

The command I use is:
```
conda env create -f envprocess.yaml
conda activate dataprocess
```

BTW your document keeps ’envprocess.yml' in [this](https://github.com/KTH-RPL/SeFlow/blob/main/dataprocess/README.md#argoverse-20), which should be replaced with 'envprocess.yaml'?

**Comment by Kin-Zhang** [comment]
Hi, Thanks for reporting, I think you can remove open3d inside envprocess.yaml (since it's only for visualization and we have that in our main env).
I will fix the documentation.
